from django.urls import path
from .views import *


urlpatterns = [
    path('register/', register),
    path('auth/', user_login),
    path('verification/send/', send),
    path('verification/check/', check),
    path('password/forgot/', forgot),
    path('password/reset/', reset),
    path('user/', user_set),
    path('user/blood/pressure/', blood_pressure),
    path('user/blood/sugar/', blood_sugar),
    path('user/weight/', user_weight),
    path('register/check/', register_check),
    path('user/diet/', user_diet),
    path('user/default/', user_default),
    path('user/setting/', user_setting),
    path('user/last-upload/', last_upload),
    path('user/records/', records),
    path('user/diary/', user_diary),
    path('user/badge/', user_badge),
    path('user/medical/', user_medical),
    path('user/a1c/', user_a1c),
    path('user/drug-used/', user_drug),
    path('user/care/', user_care),
    path('notification/', user_care),
    path('friend/code/', friend_code),
    path('friend/send/', friend_send),
    path('friend/<id>/accept/', friend_accept),
    path('friend/<id>/refuse/', friend_refuse),
    path('friend/<id>/remove/', friend_remove),
    path('friend/remove/', friends_remove),
    path('friend/remove/', friend_remove),
    path('friend/requests/', friend_requests),
    path('friend/list/', friend_list),
    path('friend/results/', friend_results),
    path('share/<type>', share),
    path('news/', news),
]
