# Generated by Django 4.1.2 on 2022-11-16 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_userprofile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a1c',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 13, 53, 44, 652046)),
        ),
        migrations.AlterField(
            model_name='diet',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 13, 53, 44, 654047)),
        ),
        migrations.AlterField(
            model_name='drug',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 13, 53, 44, 654047)),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 13, 53, 44, 651046)),
        ),
        migrations.AlterField(
            model_name='sugar',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 13, 53, 44, 652046)),
        ),
        migrations.AlterField(
            model_name='weight',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 13, 53, 44, 652046)),
        ),
    ]
