# Generated by Django 4.1.2 on 2022-11-17 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_a1c_recorded_at_alter_diet_recorded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet', to=settings.AUTH_USER_MODEL),
        ),
    ]
